config/routes.rb
Rails.application.routes.draw do

  mount Sidekiq::Web => "/sidekiq" # monitoring console
  mount API::Base => '/'

  devise_for :users, :controllers => { 
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'registrations' 
  }

  authenticated :user do
     devise_scope :user do
        root "analytics#index"
        get 'users/user_list', to: 'users#user_list', as: 'user_list'
        resources :users
        post "/users/:id/availability", to: "users#availability", as: "update_availability_user"
        delete "/users/:id/photos/:photo_id", to: "users#delete_photo", as: "delete_user_photo"
        get "/ajax_users", to: "users#ajax_users", as: "ajax_users"
        get "users/:id/followed_places", to: "users#followed_places", as: "user_followed_places"

        resources :places
        post "/places/:id/availability", to: "places#availability", as: "update_availability_place"
        delete "/places/:id/photos/:photo_id", to: "places#delete_photo", as: "delete_place_photo"
        get "/ajax_places", to: "places#ajax_places", as: "ajax_places"

        resources :photos
        get "/analytics", to: "analytics#index"
        get "/ajax_analytics_place", to: "analytics#ajax_analytics_place", as: "ajax_analytics_place"
        get "/ajax_analytics_user", to: "analytics#ajax_analytics_user", as: "ajax_analytics_user"
        get "/ajax_analytics_places_followed/:id", to: "analytics#ajax_analytics_places_followed", as: "ajax_analytics_places_followed"

        get "/notifications/new", to: "notifications#new", as: "new_notification"
        get "/notifications", to: "notifications#index", as: "notifications"
        get "/notifications/:id", to: "notifications#show", as: "notification"
        get "/ajax_notifications", to: "notifications#ajax_notifications", as: "ajax_notifications"
        post "/notifications", to: "notifications#create"

     end
  end

  unauthenticated :user do
    devise_scope :user do
      root to: "devise/sessions#new", as: "login"
      get "/users/sign_up", to: "devise/sessions#new"
    end

    get '/faq', to: 'home#faq'
    get '/terms-of-service', to: 'home#terms'
  end

end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    
  end

  def ajax_analytics_place
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: PlacesAnalyticsDatatableHandler.new(view_context) }
    end
  end

  def ajax_analytics_user
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: UsersAnalyticsDatatableHandler.new(view_context) }
    end
  end

  def ajax_analytics_places_followed
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: PlacesFollowedAnalyticsDatatableHandler.new(view_context, @user) }
    end
  end

end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/views/analytics/index.html.erb
<div class="row body_container">
  <div class="small-12 large-12 columns">
  	<h4>Places</h4>
    <table class="table-container" id="place_table">
      <thead>
        <tr>
          <th style="display: none">ID</th>
          <th>NAME</th>
          <th>FOLLOWERS</th>
          <th>TOTAL CHECK INS</th>
          <th>CURRENTLY CHECKED</th>
          <th>CHEERS</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th style="display: none">ID</th>
          <th>NAME</th>
          <th>FOLLOWERS</th>
          <th>TOTAL CHECK INS</th>
          <th>CURRENTLY CHECKED</th>
          <th>CHEERS</th>
        </tr>
      </tfoot>
    </table>
    <div class="small reveal" id="place_info_modal" data-reveal>
      <div id="place_info_container"></div>
      <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>

  <div class="small-12 large-12 columns">
    <h4>Users</h4>
    <table class="table-container" id="user_table">
      <thead>
        <tr>
          <th style="display: none">ID</th>
          <th>FIRST NAME</th>
          <th>FOLLOWED PLACES</th>
          <th>TOTAL CHECK INS</th>
          <th>TOTAL CHEERS</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th style="display: none">ID</th>
          <th>FIRST NAME</th>
          <th>FOLLOWED PLACES</th>
          <th>TOTAL CHECK INS</th>
          <th>TOTAL CHEERS</th>
        </tr>
      </tfoot>
    </table>
    <div class="small reveal" id="user_info_modal" data-reveal>
      <div id="user_info_container"></div>
      <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <div class="small reveal" id="user_followed_places_info_modal" data-reveal>
      <div id="user_followed_places_info_container"></div>
      <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
</div>

<script>
  $('#place_table').DataTable({
    "lengthMenu": [ 5,10, 25, 50, 75, 100 ],
      "processing": true,
      "serverSide": true,
      "ajax": "<%= ajax_analytics_place_url %>",
      columns: [ 
      { className: "dont_show", searchable: false, orderable: false }, 
      { }, 
      { searchable: false }, 
      { searchable: false },
      { searchable: false },  
      { searchable: false }, 
      ] 
  });

  $('#user_table').DataTable({
    "lengthMenu": [ 5,10, 25, 50, 75, 100 ],
      "processing": true,
      "serverSide": true,
      "ajax": "<%= ajax_analytics_user_url %>",
      columns: [ 
      { className: "dont_show", searchable: false, orderable: false }, 
      { }, 
      { searchable: false }, 
      { searchable: false },
      { searchable: false },  
      ] 
  });
</script>