config/routes.rb
Rails.application.routes.draw do

  mount Sidekiq::Web => "/sidekiq" # monitoring console
  mount API::Base => '/'

  devise_for :users, :controllers => { 
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'registrations' 
  }

  authenticated :user do
     devise_scope :user do
        root "analytics#index"
        get 'users/user_list', to: 'users#user_list', as: 'user_list'
        resources :users
        post "/users/:id/availability", to: "users#availability", as: "update_availability_user"
        delete "/users/:id/photos/:photo_id", to: "users#delete_photo", as: "delete_user_photo"
        get "/ajax_users", to: "users#ajax_users", as: "ajax_users"
        get "users/:id/followed_places", to: "users#followed_places", as: "user_followed_places"

        resources :places
        post "/places/:id/availability", to: "places#availability", as: "update_availability_place"
        delete "/places/:id/photos/:photo_id", to: "places#delete_photo", as: "delete_place_photo"
        get "/ajax_places", to: "places#ajax_places", as: "ajax_places"

        resources :photos
        get "/analytics", to: "analytics#index"
        get "/ajax_analytics_place", to: "analytics#ajax_analytics_place", as: "ajax_analytics_place"
        get "/ajax_analytics_user", to: "analytics#ajax_analytics_user", as: "ajax_analytics_user"
        get "/ajax_analytics_places_followed/:id", to: "analytics#ajax_analytics_places_followed", as: "ajax_analytics_places_followed"

        get "/notifications/new", to: "notifications#new", as: "new_notification"
        get "/notifications", to: "notifications#index", as: "notifications"
        get "/notifications/:id", to: "notifications#show", as: "notification"
        get "/ajax_notifications", to: "notifications#ajax_notifications", as: "ajax_notifications"
        post "/notifications", to: "notifications#create"

     end
  end

  unauthenticated :user do
    devise_scope :user do
      root to: "devise/sessions#new", as: "login"
      get "/users/sign_up", to: "devise/sessions#new"
    end

    get '/faq', to: 'home#faq'
    get '/terms-of-service', to: 'home#terms'
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  birthdate                       :string
#  created_at                      :datetime         not null
#  current_sign_in_at              :datetime
#  current_sign_in_ip              :inet
#  deleted_at                      :datetime
#  email                           :string           default(""), not null
#  encrypted_password              :string           default(""), not null
#  facebook_url                    :string
#  first_name                      :string
#  gender                          :integer          default(0), not null
#  help                            :boolean          default(FALSE)
#  hide_profile_at                 :datetime
#  hide_profile_with_zero_check_in :boolean          default(FALSE)
#  id                              :integer          not null, primary key
#  image_url                       :string
#  last_name                       :string
#  last_sign_in_at                 :datetime
#  last_sign_in_ip                 :inet
#  notify_activity                 :boolean          default(TRUE)
#  notify_cheers                   :boolean          default(TRUE)
#  notify_drinks                   :boolean          default(TRUE)
#  notify_messages                 :boolean          default(TRUE)
#  prefers_men                     :boolean          default(FALSE)
#  prefers_women                   :boolean          default(FALSE)
#  remember_created_at             :datetime
#  reset_password_sent_at          :datetime
#  reset_password_token            :string
#  role                            :integer          default(0), not null
#  sign_in_count                   :integer          default(0), not null
#  uid                             :string           default(""), not null
#  updated_at                      :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  DEFAULT_DRINK_CREDITS = 5
  include UID

  acts_as_reader
  after_create :generate_user_setting
  devise :database_authenticatable, :omniauthable,
    :recoverable, :rememberable, :trackable, :validatable

  scope :except_self, ->(user) { where("users.id != ? and users.deleted_at IS NULL", user.id)}
  scope :with_total_check_ins_here, -> { select('users.*, (SELECT count(*) from check_ins where check_ins.user_id = users.id)  AS total_check_ins_here') }
  scope :with_total_check_ins_for_place, -> (place_id) { select('users.*, (SELECT count(*) from check_ins where check_ins.user_id = users.id)  AS total_check_ins_here') }
  scope :who_checked_in_here, -> (place_id){ joins(:check_ins).where('check_ins.place_id = ? AND check_ins.created_at <= check_ins.expires_at AND check_ins.expires_at >= ?', place_id ,DateTime.now).order("check_ins.expires_at DESC") }

  enum gender: { not_specified: 0, male: 1, female: 2 }
  enum role: { normal: 0, admin: 1 }

  validates_presence_of     :email
  validates_uniqueness_of   :email

  has_many :follows, dependent: :destroy
  has_many :place_followed, through: :follows, source: :place do
    def recent
      order('follows.created_at DESC')
    end
  end
  has_many :check_ins
  has_many :place_check_ins, through: :check_ins, source: :place
  has_many :conversation_memberships, foreign_key: "member_id"
  has_many :conversations, through: :conversation_memberships
  has_many :photos, as: :imageable, dependent: :destroy

  has_many :transactions, class_name: 'ProductTransaction'
  has_many :products, through: :transactions 

  has_many :api_keys, dependent: :destroy

  has_many :block_lists, dependent: :destroy
  has_many :blocked_profiles, through: :block_lists, source: :blockable, source_type: "User"
  has_many :blocked_places, through: :block_lists, source: :blockable, source_type: "Place"

  has_many :blocked_me_lists, source: :blockable, source_type: "User", class_name: "BlockList", foreign_key: "blockable_id"
  has_many :blocked_me_profiles, through: :blocked_me_lists, class_name: "User", source: :user

  has_many :cheers_with_initiatees, -> { where workflow_state: "cheers" }, class_name: "Interaction", foreign_key: :initiator_id
  has_many :cheers_with_initiators, -> { where workflow_state: "cheers" }, class_name: "Interaction", foreign_key: :initiatee_id
  has_many :contacts_initiatee, through: :cheers_with_initiatees, source: :initiatee
  has_many :contacts_initiator, through: :cheers_with_initiators, source: :initiator

  has_many :devices, dependent: :destroy

  has_many :activity_memberships, foreign_key: :member_id, dependent: :destroy
  has_many :places_activities, through: :activity_memberships, source: :places_activity
  has_many :cheers_check_in_activities, through: :activity_memberships, source: :cheers_check_in_activity
  has_many :tipple_notifications, through: :activity_memberships, source: :tipple_notification

  has_many :identities, dependent: :destroy

  has_many :manual_notifications, dependent: :destroy #User who sent the notif

  scope :all_except, ->(user) { where.not(id: user) }
  scope :not_deleted, -> { where(deleted_at: nil) }

  scope :for_analytics, ->  { joins("LEFT OUTER JOIN follows ON follows.user_id = users.id 
                                     LEFT OUTER JOIN check_ins ON check_ins.user_id = users.id 
                                     LEFT OUTER JOIN interactions ON (interactions.initiator_id = users.id OR interactions.initiatee_id = users.id) AND interactions.workflow_state = 'cheers'")
    .select('users.id, users.first_name,
                                     count(distinct(follows.id)) as followed_place_count, 
                                     count(distinct(check_ins.id)) as check_ins_count,
                                     count(distinct(interactions.id)) as cheers_with_count
  ')
    .group('users.id')
  }

  ATTRIBUTE_METHODS = ["prefers_men", "prefers_women", "notify_drinks", "notify_cheers", "notify_messages", "notify_activity", "hide_profile_with_zero_check_in", "hide_profile_at", "deleted_at"]

  ["prefers_men","prefers_women"].each do |p|
    define_method("is_#{p.downcase}") do
      p.downcase == true
    end
  end

  ATTRIBUTE_METHODS.each do |t|
    define_method("toggle_#{t.downcase}") do
      if(t == "hide_profile_at")
        self.hide_profile_at? ? self.update_attributes(hide_profile_at: nil) : self.update_attributes(hide_profile_at: (DateTime.now + 24.hour).iso8601)
      elsif (t == "deleted_at")
        self.deleted_at? ? self.update_attributes(deleted_at: nil) : self.update_attributes(deleted_at: DateTime.now.iso8601)
      else
        self.send("#{t}?") ? self.update_attribute(t.to_sym, false) : self.update_attribute(t.to_sym, true)
      end

      # if both prefers_men && prefers_women is false, preselect the opposite
      # of the toggled attribute i.e. prefers_men=false, prefers_women=true
      if !prefers_women? && !prefers_men?
        self.update_attribute(:prefers_men, true) if t == 'prefers_women'
        self.update_attribute(:prefers_women, true) if t == 'prefers_men'
      end
    end
  end

  def avatar
    self.photos.find_by(position: 0).try(:image)
  end

  def delete_previous_api_keys
    api_keys.first.delete if api_keys.count > 5
  end

  def active_for_authentication?
    super && self.admin?
  end

  def inactive_message
    "Please enter an Admin account"
  end

  def self.reader_scope
    not_deleted
  end

  def has_read? message
    message.sender_id == self.id || self.have_read?(message)
  end

  def self.search(search)
    where('first_name iLIKE :search OR last_name iLIKE :search OR email iLIKE :search', search: "%#{search}%").order(:first_name)  
  end

  def prefers? (users)
    pass = []
    users.each do | user |
      pass << user if user.preferences.include?(self[:gender]) && self.preferences.include?(user[:gender])
    end
    pass
  end

  def preferences
    g = []
    g << 1 if prefers_men?
    g << 2 if prefers_women?
    if g.empty?
      (male?) ? g << 2 : g << 1
    end
    g
  end

  def age
    if self.birthdate.present?
      now = Time.now.utc.to_date
      dob = self.birthdate.to_date
      now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
    end
  end

  def is_deleted?
    !deleted_at.nil?
  end

  def has_credits?
    credits_left_count > 0
  end

  def credits_left
    if has_unlimited_likes?
      "Unlimited"
    else
      credits_left_count.to_s
    end
  end

  def credits_left_count
    likes_purchased = self.products.map { |entry| entry.value }.sum
    check_in_likes = self.check_ins.map {|check_in| check_in.random_likes + check_in.shared_likes }.sum
    total_likes = likes_purchased + check_in_likes
    DEFAULT_DRINK_CREDITS + (total_likes - used_credits) #total_people_i_liked minus people_i_liked when im in unlimited subscription.
  end

  def used_credits
    group1 = self.interactions.joins(:histories).where('(interaction_histories.state_changed_to = ? AND interaction_histories.state_from = ?)', 'drink', 'like').count
    entries = self.transactions.with_expiration
    group2 = entries.map { |entry| self.interactions.joins(:histories).all_likes_history.within(entry.created_at,entry.expires_at).count }.sum
    group1 - group2
  end

  def total_cheers
    self.interactions.joins(:histories).all_cheers_history.count
  end

  def interactions
    Interaction.where("initiator_id = :id OR initiatee_id = :id",id: self.id)
  end

  def interaction_status_with(current_user,place)
    last_interaction = self.interactions.where("(initiator_id = :id OR initiatee_id = :id) AND workflow_state = 'cheers'",id: current_user).last
    last_interaction || self.interactions.where("(initiator_id = :id OR initiatee_id = :id) AND place_id = :place",id: current_user,place: place).last
  end

  def likers

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  check_authorization
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :delete, :delete_photo, :followed_places]

  def index 
    @users = if params[:search]
      User.all_except(current_user).search(params[:search]).order("first_name ASC")
    else
      User.all_except(current_user).order('first_name ASC')
    end
    @create_path = users_path 
    respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @user }
      end
  end


  def new
    @user = User.new
    respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @user }
      end
  end

  def create
        respond_to do |format|
        if @user.save
          @user.photos.create(image: params[:user][:add_photo], position: @user.photos.count + 1) if params[:user][:add_photo].present?
          format.html { redirect_to users_path, notice: 'User was successfully created.' }
          format.json { render json: @user, status: :created, location: @user }
        else
          format.html { render action: "new" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
  end

  def edit
    
  end

  def update
    if user_params[:password].blank?
      update_params = user_params_without_password
    else
      update_params = user_params
    end
    if @user.birthdate.present? 
      update_params[:birthdate] = update_params[:birthdate] + @user.birthdate[10..-1]
    else
      update_params[:birthdate] = update_params[:birthdate] + DateTime.now.to_s[10..-1]
    end

    respond_to do |format|
        if @user.update(update_params)
          params[:user][:photos].each_with_index { |v, k| @user.photos.find(v).update(position: k) } if params[:user][:photos].present?
          @user.photos.create(image: params[:user][:add_photo], position: @user.photos.count) if params[:user][:add_photo].present?
          format.html { redirect_to users_path, notice: 'User was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
  end

  def show
    respond_to do |format|
      format.html { render nothing: true }
      format.js 
    end
  end

  def destroy
    @user.update(deleted_at: DateTime.now)
    respond_to do |format|
        format.html { redirect_to users_path }
        format.json { head :no_content }
      end
  end

  def availability
    @user.deleted_at.present? ? @user.update(deleted_at: nil) : @user.update(deleted_at: DateTime.now)
    respond_to do |format|
      format.html { render nothing: true }
      format.js 
    end
  end

  def delete_photo
    @photo = @user.photos.find(params[:photo_id])
    @photo.destroy
    @user.photos.order(position: :asc).map(&:id).each_with_index { |v, k| @user.photos.find(v).update(position: k) }
    respond_to do |format|
      format.html { redirect_to ponies_url }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  def ajax_users
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: UsersDatatableHandler.new(view_context) }
    end
  end

  def followed_places
    respond_to do |format|
      format.html { render nothing: true }
      format.js 
    end
  end

  def user_list
    @users = User.not_deleted.all.where("email iLike ?", "%#{params[:q]}%").order(email: "ASC").limit(5)
    render json: @users.map { |hash|  { id: hash[:id] ,email: hash[:email] } }
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params[:user][:photos] ||= []
    params[:user][:add_photo] ||= nil
    params.require(:user).permit(:email, :first_name, :last_name, :gender, :birthdate, :avatar, :role, :password, :password_confirmation)
  end

  def user_params_without_password
    params[:user][:photos] ||= []
    params[:user][:add_photo] ||= nil
    params.require(:user).permit(:email, :first_name, :last_name, :gender, :birthdate, :avatar, :role)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_followed_place_info.html.erb
<div class="row">
  <% 
    if @user.avatar.present? 
      user_avatar = @user.avatar.url(:large)
    else
      @user.male? ? user_avatar = Photo.default_photo_men.try(:image).url(:large) : user_avatar = Photo.default_photo_women.try(:image).url(:large)
    end 
  %>
  <div class="info_icon_container" style="background-image: url(<%= user_avatar %>); background-position: center center; background-repeat: no-repeat; background-size: cover;">
  </div>
</div>

<div class="row info_container1">
  <div class="small-12 large-12 columns">
    <h4>Followed places</h4>
    <table class="table-container" id="followed_place_table">
      <thead>
        <tr>
          <th style="display: none">ID</th>
          <th>NAME</th>
          <th>CHECKINS</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th style="display: none">ID</th>
          <th>NAME</th>
          <th>CHECKINS</th>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

<script>
  $('#followed_place_table').DataTable({
    "lengthMenu": [ 5,10, 25, 50, 75, 100 ],
      "processing": true,
      "serverSide": true,
      "ajax": "<%= ajax_analytics_places_followed_path(@user) %>",
      columns: [ 
      { className: "dont_show", searchable: false, orderable: false }, 
      { }, 
      { searchable: false }, 
      ] 
  });
</script>

app/views/users/_form.html.erb
<div class="row body_container">
  <div class="form_container">
    <% if @user.errors.any? %>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %>

    <%= form_for @user,  html: { multipart: true } do |f| %>
      <div class="small-3 large-3 columns info_label">
        Email:
      </div>
      <div class="small-9 large-9 columns">
        <%= f.email_field :email, autofocus: true, placeholder: "Email", required: true  %>
      </div>

      <div class="small-3 large-3 columns info_label">
        First Name:
      </div>
      <div class="small-9 large-9 columns">
        <%= f.text_field :first_name, autofocus: true, placeholder: "First Name", required: true %>
      </div>

      <div class="small-3 large-3 columns info_label">
        Last Name:
      </div>
      <div class="small-9 large-9 columns">
        <%= f.text_field :last_name, autofocus: true, placeholder: "Last Name", required: true %>
      </div>

      <div class="small-3 large-3 columns info_label">
        Gender:
      </div>
      <div class="small-9 large-9 columns">
        <%= f.select(:gender, User.genders.keys.map {|gender| [gender.titleize,gender]} ) %>
      </div>

      <div class="small-3 large-3 columns info_label">
        Role:
      </div>
      <div class="small-9 large-9 columns">
        <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]} ) %>
      </div>

      <div class="small-3 large-3 columns info_label">
        Birthdate:
      </div>
      
      <div class="small-9 large-9 columns date">
          <% 
            @user.birthdate.present? ? birthdate =  @user.birthdate.first(10) : birthdate = "1970-01-15" 
          %>
          <input type="text" value= "<%= birthdate %>" name="user[birthdate]" id="user_birthdate" readonly>
      </div>
      <div class="small-3 large-3 columns info_label">
        Password:
      </div>
      <div class="small-9 large-9 columns">
        <%= f.password_field :password, autocomplete: "off" %>
      </div>

      <div class="small-3 large-3 columns info_label">
        Confirm
      </div>
      <div class="small-9 large-9 columns">
        <%= f.password_field :password_confirmation, autocomplete: "off" %>
      </div>

      <% if !(@user.photos.count <= 0) ||  @user.photos.count <= 4 %>
      <div class="small-3 large-3 columns info_label">
        Add photo:
      </div>
      <div class="small-9 large-9 columns">
        <%= f.file_field :add_photo %>
      </div>
      <% end %>

      <% if !(@user.photos.count <= 0) %>
      <div class="small-3 large-3 columns info_label">
        Order:
      </div>
      <div class="small-9 large-9 columns">
        <div class="sortable">
        <% @user.photos.order(position: :asc).each { |photo| %>
          <div class="ui-state-default" style="background-image: url(<%= photo.try(:image).url(:medium) %>); background-position: center center; background-repeat: no-repeat; background-size: cover;">
            <%= f.hidden_field(:photos, multiple: true, value: photo.id) %>
            <%= link_to raw('&times;'), delete_user_photo_path(id: @user.id, photo_id: photo.id), method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: 'delete_photo' %>
          </div>
        <%  } %>
        </div> 
        <br>
      </div>
      <% end %>

      <div class="small-12 large-12 columns">
        <div class="actions">
          <br>
          <%= link_to "USERS", users_path, class: "violet_button" %>  <%= f.submit "SUBMIT", class: "green_button"%>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script>
  $(function() {
    $( ".sortable" ).sortable({
      revert: true
    });
    $( ".sortable, .ui-state-default" ).disableSelection();
    $('.delete_photo').bind('ajax:success', function(e) {  
        $(this).parent().remove();
    })

    $('#user_birthdate').fdatepicker({
      format: 'yyyy-mm-dd',
      disableDblClickSelection: true
    });
  });
</script>

app/views/users/_info.html.erb
<div class="row">
  <% 
    if @user.avatar.present? 
      user_avatar = @user.avatar.url(:large)
    else
      @user.male? ? user_avatar = Photo.default_photo_men.try(:image).url(:large) : user_avatar = Photo.default_photo_women.try(:image).url(:large)
    end 
  %>
  <div class="info_icon_container" style="background-image: url(<%= user_avatar %>); background-position: center center; background-repeat: no-repeat; background-size: cover;">
  </div>
</div>

<div class="row info_container1">
  <div class="small-6 large-6 columns info_label">
    <span>Email:</span><br>
    <span>First Name:</span><br>
    <span>Last Name:</span><br>
    <span>Gender:</span><br>
    <span>Age:</span><br>
    <span>Role:</span><br>
  </div>
  <div class="small-6 large-6 columns info_text">
    <span><%= @user.email %></span><br>
    <span><%= @user.first_name %></span><br>
    <span><%= @user.last_name %></span><br>
    <span><%= @user.gender %></span><br>
    <span><%= @user.age %></span><br>
    <span><%= @user.role %></span><br>
  </div>
</div>
<div class="row info_container2">
  <div class="small-12 large-12 columns">
    <div style="width: 500px; margin-left: auto; margin-right: auto; text-align: center;">
      <div class="photo_gallery">
        <% 
        if @user.photos.present?
        @user.photos.order(position: :asc).each { |photo| %>
          <div class="slick-slide">
            <div class="photo" style="background-image: url(<%= photo.try(:image).url(:medium) %>); background-position: center center; background-repeat: no-repeat; background-size: cover;" >
            </div>
          </div>
        <%  } 
        end%>
      </div>
      <br>
      <%= link_to "USERS", users_path, class: "violet_button" %>  <%= link_to "EDIT", edit_user_path(@user), class: "green_button" %>
    </div>
  </div>
</div>


<script type="text/javascript">
  $(document).ready(function(){
    $('.photo_gallery').slick({
      accessibility: true,
      arrows: true,
      dots: true,
      infinite: true,
      speed: 300,
      slidesToShow: 3,
      slidesToScroll: 1,
      responsive: [
        {
          breakpoint: 1024,
          settings: {
            slidesToShow: 3,
            slidesToScroll: 3,
            infinite: true,
            dots: true
          }
        },
        {
          breakpoint: 600,
          settings: {
            slidesToShow: 2,
            slidesToScroll: 2
          }
        },
        {
          breakpoint: 480,
          settings: {
            slidesToShow: 1,
            slidesToScroll: 1
          }
        }
        // You can unslick at a given breakpoint now by adding:
        // settings: "unslick"
        // instead of a settings object
      ]
    });
  });
</script>

app/views/users/availability.js.erb
<% @user.deleted_at.present? ? availability = "ACTIVATE" : availability = "DEACTIVATE" %>
$("#availability_<%=@user.id%>").html('<%=availability%>');

app/views/users/edit.html.erb
<%= render "form"%>

app/views/users/followed_places.js.erb
$("#user_followed_places_info_container").html('');
$("#user_followed_places_info_modal").foundation('open');
$("#user_followed_places_info_container").html('<%= j render "followed_place_info", xray: false %>');

app/views/users/index.html.erb
<div class="row body_container">
  <div class="small-12 large-12 columns">
    <table class="table-container" id="user_table">
      <thead>
        <tr>
          <th style="display: none">ID</th>
          <th>EMAIL</th>
          <th>FIRST NAME</th>
          <th>LAST NAME</th>
          <th>GENDER</th>
          <th>AGE</th>
          <th>ROLE</th>
          <th>AVATAR</th>
          <th>ACTION</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th style="display: none">ID</th>
          <th>EMAIL</th>
          <th>FIRST NAME</th>
          <th>LAST NAME</th>
          <th>GENDER</th>
          <th>AGE</th>
          <th>ROLE</th>
          <th>AVATAR</th>
          <th>ACTION</th>
        </tr>
      </tfoot>
    </table>
    <div class="small reveal" id="user_info_modal" data-reveal>
      <div id="user_info_container"></div>
      <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
</div>

<script>
  // $('#user_table').DataTable({
  //   "lengthMenu": [ 5,10, 25, 50, 75, 100 ],
  // });

  $('#user_table').DataTable({
    "lengthMenu": [ 5,10, 25, 50, 75, 100 ],
      "processing": true,
      "serverSide": true,
      "ajax": "<%= ajax_users_url %>",
      columns: [ 
      { className: "dont_show", searchable: false, orderable: false }, 
      { }, 
      { },
      { }, 
      { searchable: false },
      { searchable: false },
      { searchable: false },
      { searchable: false, orderable: false },
      { searchable: false, orderable: false } 
      ] 
  });
</script>

app/views/users/new.html.erb
<%= render "form"%>

app/views/users/show.js.erb
$("#user_info_container").html('');
$("#user_info_modal").foundation('open');
$("#user_info_container").html('<%= j render "info", xray: false %>');