config/routes.rb
Rails.application.routes.draw do

  mount Sidekiq::Web => "/sidekiq" # monitoring console
  mount API::Base => '/'

  devise_for :users, :controllers => { 
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'registrations' 
  }

  authenticated :user do
     devise_scope :user do
        root "analytics#index"
        get 'users/user_list', to: 'users#user_list', as: 'user_list'
        resources :users
        post "/users/:id/availability", to: "users#availability", as: "update_availability_user"
        delete "/users/:id/photos/:photo_id", to: "users#delete_photo", as: "delete_user_photo"
        get "/ajax_users", to: "users#ajax_users", as: "ajax_users"
        get "users/:id/followed_places", to: "users#followed_places", as: "user_followed_places"

        resources :places
        post "/places/:id/availability", to: "places#availability", as: "update_availability_place"
        delete "/places/:id/photos/:photo_id", to: "places#delete_photo", as: "delete_place_photo"
        get "/ajax_places", to: "places#ajax_places", as: "ajax_places"

        resources :photos
        get "/analytics", to: "analytics#index"
        get "/ajax_analytics_place", to: "analytics#ajax_analytics_place", as: "ajax_analytics_place"
        get "/ajax_analytics_user", to: "analytics#ajax_analytics_user", as: "ajax_analytics_user"
        get "/ajax_analytics_places_followed/:id", to: "analytics#ajax_analytics_places_followed", as: "ajax_analytics_places_followed"

        get "/notifications/new", to: "notifications#new", as: "new_notification"
        get "/notifications", to: "notifications#index", as: "notifications"
        get "/notifications/:id", to: "notifications#show", as: "notification"
        get "/ajax_notifications", to: "notifications#ajax_notifications", as: "ajax_notifications"
        post "/notifications", to: "notifications#create"

     end
  end

  unauthenticated :user do
    devise_scope :user do
      root to: "devise/sessions#new", as: "login"
      get "/users/sign_up", to: "devise/sessions#new"
    end

    get '/faq', to: 'home#faq'
    get '/terms-of-service', to: 'home#terms'
  end

end

app/models/place.rb
# == Schema Information
#
# Table name: places
#
#  address     :string
#  created_at  :datetime         not null
#  deleted_at  :datetime
#  description :string
#  id          :integer          not null, primary key
#  lat         :float
#  lng         :float
#  name        :string
#  updated_at  :datetime         not null
#

class Place < ActiveRecord::Base
  DEFAULT_DESCRIPTION = 'No description has been added for this place just yet, try checking back again later!'
  VALID_DISTANCE = 0.1 # 100 meters
  geocoded_by :address, latitude: :lat, longitude: :lng
  has_many :follows
  has_many :followers, through: :follows, source: :user
  has_many :check_ins
  has_many :user_check_ins, through: :check_ins, source: :user
  has_many :photos, as: :imageable
  has_many :interactions
  # define method  for this since it's now under interaction
  # has_many :interaction_histories
  has_many :activities, class_name: "Activities::PlacesActivity", foreign_key: :source_id

  scope :not_deleted, ->{ where(deleted_at: nil)}
  scope :filtered_by_name, -> (place_name) { where("places.name iLIKE ?", place_name) }
  scope :filtered_by_address, -> (place_address) { where("places.address iLIKE ?", place_address) }

  #My goal for this is to have names for the counts of 
  #followers, total_check_ins, currently_checked_in and cheers 
  #that will be used in column sorting on place_analytics_handler
  scope :for_analytics, ->  { joins("LEFT OUTER JOIN follows ON follows.place_id = places.id 
                                     LEFT OUTER JOIN check_ins ON check_ins.place_id = places.id 
                                     LEFT OUTER JOIN interactions ON interactions.place_id = places.id
                                     LEFT OUTER JOIN interaction_histories ON interactions.id = interaction_histories.interaction_id AND interaction_histories.state_changed_to = 'cheers'
                                     ")
                              .select('places.id, places.name,
                                     count(distinct(follows.id)) as followers_count, 
                                     count(distinct(check_ins.id)) as check_ins_count,
                                     count(distinct(check_ins.expires_at >= now())) as currently_check_ins_count,
                                     count(distinct(interaction_histories.id)) as cheers_count')
                              .group('places.id')
                            }
  scope :for_places_followed_analytics, -> (user)  {
                              joins("LEFT OUTER JOIN check_ins ON check_ins.place_id = places.id and check_ins.user_id = " + user.id.to_s )
                              .select('places.id, places.name, 
                                     count(distinct(check_ins.id)) as check_ins_here_count
                                     ')
                              .group('places.id')
                            }          
 
  validates :name, uniqueness: true
  validates_presence_of :name,:address,:lat,:lng   
  validates :description, length: { maximum: 140 }, allow_blank: true

  def background
    self.photos.find_by(position: 0).try(:image)
  end

  def self.search(search)
    where('name iLIKE :search', search: "%#{search}%").order(:name)  
  end

  def interaction_histories
    history_ids = interactions.map{|i| i.histories.map(&:id)}.flatten
    InteractionHistory.where(id: history_ids)
  end

  def self.get_near_places(lat,lng)
    near([lat, lng], 100.0, { units: :km })
  end

  def user_interactions(sender, recipient)
    check_ins.availability.where(user_id: sender).last.interactions.where(recipient_id: recipient)
  end

  def unfollow_by(user)
    follows.find_by(user: user) ? follows.find_by(user: user).destroy : false
  end

  def follow_by(user)
    follows.create(user: user)
  end

  def followed_by?(user)
    self.followers.include?(user)
  end

  def description
    if super.blank?
      DEFAULT_DESCRIPTION
    else
      super
    end
  end


  def check_in(user,random_likes,lat,lng)
    #0.010 = 10meters
    if Place.valid_random_likes?(random_likes.to_i) && Place.valid_distance?(self.distance_to([lat,lng]))
      if user.check_ins.availability.empty?
        follows.build(user: user).save unless followers.include?(user)
        check_ins.build(user: user, random_likes: random_likes).save
      else
        if user.check_ins.availability.last.place.id != self.id
          user.check_ins.availability.last.update(expires_at: DateTime.now)
          follows.build(user: user).save unless followers.include?(user)
          check_ins.build(user: user, random_likes: random_likes).save
        end
      end
    end
  end

  def self.valid_distance?(distance)
    (0..VALID_DISTANCE).include?(distance)
  end

  def self.valid_random_likes?(random_likes)
    (1..10).include?(random_likes)
  end

  before_save do
    self.name.capitalize!
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  load_and_authorize_resource
  check_authorization
  before_action :authenticate_user!
  before_action :set_place, only: [:show, :edit, :update, :delete, :delete_photo]

  def index
    @places = if params[:search] 
      Place.search(params[:search]).order("name ASC")
    else
      Place.order('name ASC')
    end
    @create_path = places_path
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @places }
    end
  end

  def new
    @place = Place.new
    respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @place }
      end
  end

  def create
    respond_to do |format|
      if @place.save
        if params[:place][:add_photo].present?
          params[:place][:add_photo].each do | photo |
            @place.photos.create(image: photo, position: @place.photos.count + 1)
          end
        end
        format.html { redirect_to places_path, notice: 'Place was successfully created.' }
        format.json { render json: @place, status: :created, location: @place }
      else
        format.html { render action: "new" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @place.update(place_params)
        params[:place][:photos].each_with_index { |v, k| @place.photos.find(v).update(position: k)} if params[:place][:photos].present?
        
        if params[:place][:add_photo].present?
          params[:place][:add_photo].each do | photo |
            @place.photos.create(image: photo, position: @place.photos.count + 1)
          end
        end

        format.html { redirect_to places_path, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    respond_to do |format|
      format.html { render nothing: true }
      format.js 
    end
  end

  def destroy
    @place.destroy
    respond_to do |format|
        format.html { redirect_to places_path }
        format.json { head :no_content }
      end
  end

  def availability
    @place.deleted_at.present? ? @place.update(deleted_at: nil) : @place.update(deleted_at: DateTime.now)
    respond_to do |format|
      format.html { render nothing: true }
      format.js 
    end
  end

  def delete_photo
    @photo = @place.photos.find(params[:photo_id])
    @photo.destroy
    @place.photos.order(position: :asc).map(&:id).each_with_index { |v, k| @place.photos.find(v).update(position: k) }
    respond_to do |format|
      format.html { redirect_to ponies_url }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  def ajax_places
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: PlacesDatatableHandler.new(view_context) }
    end
  end

  private

  def set_place
      @place = Place.find(params[:id])
    end

  def place_params
    params[:place][:photos] ||= []
    params[:place][:add_photo] ||= []
    params.require(:place).permit(:name, :address, :description, :lat, :lng)
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<div class="row body_container">
  <div class="form_container">
    <% if @place.errors.any? %>
    <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>
    <%= form_for @place,  html: { multipart: true } do |f| %>
      <div class="small-3 large-3 columns info_label">
        Name:
      </div>
      <div class="small-9 large-9 columns">
        <%= f.text_field :name, autofocus: true, placeholder: "Name", required: true %>
      </div>

      <div class="small-3 large-3 columns info_label">
        Address:
      </div>
      <div class="small-9 large-9 columns">
        <%= f.text_area :address, autofocus: true, placeholder: "Address", required: true %>
      </div>

      <div class="small-3 large-3 columns info_label">
        Description:
      </div>

      <div class="small-9 large-9 columns">
        <%= f.text_field :description, autofocus: true, placeholder: "Description" %>
      </div>

      <div class="small-3 large-3 columns info_label">
        Latitude:
      </div>
      <div class="small-9 large-9 columns">
        <%= f.number_field :lat, step: 'any', autofocus: true, placeholder: "00.00000", required: true %>
      </div>

      <div class="small-3 large-3 columns info_label">
        Longitude:
      </div>
      <div class="small-9 large-9 columns">
        <%= f.number_field :lng, step: 'any', autofocus: true, placeholder: "00.00000", required: true %>
      </div>

      <div class="small-3 large-3 columns info_label">
        Add photo:
      </div>
      <div class="small-9 large-9 columns">
        <br/>
        <div id="append_container">
          <div class="add_photo_container">
            <div class="small-1 large-1 columns">
              <button class="remove-button" aria-label="Close alert" type="button">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="small-11 large-11 columns">
            <%= f.file_field :add_photo, multiple: true, name: "place[add_photo][]", class: "place_add_photo" %> 
            </div>
          </div>
        </div>
      </div>

      <div class="small-3 large-3 columns">
        &nbsp;
      </div>
      <div class="small-9 large-9 columns right-text-align">
        <a id="add_more">Add more</a>
      </div>

      <% if !(@place.photos.count <= 0) %>
      <div class="small-3 large-3 columns info_label">
        Order:
      </div>
      <div class="small-9 large-9 columns">
        <div class="sortable">
        <% @place.photos.order(position: :asc).each { |photo| %>
          <div class="ui-state-default" style="background-image: url(<%= photo.try(:image).url(:medium) %>); background-position: center center; background-repeat: no-repeat; background-size: cover;">
            <%= f.hidden_field(:photos, multiple: true, value: photo.id) %>
            <%= link_to raw('&times;'), delete_place_photo_path(id: @place.id, photo_id: photo.id), method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: 'delete_photo' %>
          </div>
        <%  } %>
        </div> 
        <br>
      </div>
      <% end %>

      <div class="small-12 large-12 columns">
        <div class="actions">
          <br>
          <%= link_to "PLACES", places_path, class: "violet_button" %>  <%= f.submit "SUBMIT", class: "green_button" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script>
  $("#add_more").click(function(e){
    $("#append_container").append(getInsert);
  });

  $(document).on('click', ".remove-button", function () { 
     $(this).parent('div').parent(".add_photo_container").remove();
  });


  clone = $("#append_container").first('div').html();

  function getInsert(){
    return  clone
  }

  $(function() {
    $( ".sortable" ).sortable({
      revert: true
    });
    $( ".sortable, .ui-state-default" ).disableSelection();
    
    $('.delete_photo').bind('ajax:success', function(e) {  
        $(this).parent().remove();
    })
  });
</script>

app/views/places/_info.html.erb
<div class="row">
  <% 
    if @place.background.present? 
      place_background = @place.background.url(:large)
    else
      place_background = Photo.default_photo_place.try(:image).url(:large)
    end 
  %>
  <div class="info_icon_container" style="background-image: url(<%= place_background %>); background-position: center center; background-repeat: no-repeat; background-size: cover;">
  </div>
</div>

<div class="row info_container1">
  <div class="small-6 large-6 columns info_label">
    <span>Name:</span><br>
    <span>Address:</span><br>
    <span>Latitude:</span><br>
    <span>Longitude:</span><br> 
  </div>
  <div class="small-6 large-6 columns info_text">
    <span><%= @place.name %></span><br>
    <span><%= @place.address %></span><br>
    <span><%= @place.lat %></span><br>
    <span><%= @place.lng %></span><br>
  </div>
</div>
<div class="row info_container2">
  <div class="small-12 large-12 columns">
    <div style="width: 500px; margin-left: auto; margin-right: auto; text-align: center;">
      <div class="photo_gallery">
        <% 
        if @place.photos.present?
        @place.photos.order(position: :asc).each { |photo| %>
          <div class="slick-slide">
            <div class="photo" style="background-image: url(<%= photo.try(:image).url(:medium) %>); background-position: center center; background-repeat: no-repeat; background-size: cover;" >
            </div>
          </div>
        <% } 
        end
        %>
      </div>
      <br>
      <%= link_to "PLACES", places_path, class: "violet_button" %>  <%= link_to "EDIT", edit_place_path(@place), class: "green_button" %>
    </div>
  </div>
</div>


<script type="text/javascript">
  $(document).ready(function(){
    $('.photo_gallery').slick({
      accessibility: true,
      arrows: true,
      dots: true,
      infinite: true,
      speed: 300,
      slidesToShow: 3,
      slidesToScroll: 1,
      responsive: [
        {
          breakpoint: 1024,
          settings: {
            slidesToShow: 3,
            slidesToScroll: 3,
            infinite: true,
            dots: true
          }
        },
        {
          breakpoint: 600,
          settings: {
            slidesToShow: 2,
            slidesToScroll: 2
          }
        },
        {
          breakpoint: 480,
          settings: {
            slidesToShow: 1,
            slidesToScroll: 1
          }
        }
        // You can unslick at a given breakpoint now by adding:
        // settings: "unslick"
        // instead of a settings object
      ]
    });
  });
</script>

app/views/places/availability.js.erb
<% @place.deleted_at.present? ? availability = "ACTIVATE" : availability = "DEACTIVATE" %>
$("#availability_<%=@place.id%>").html('<%=availability%>');

app/views/places/edit.html.erb
<%= render "form"%>

app/views/places/index.html.erb
<div class="row body_container">
  <div class="small-12 large-12 columns">
    <table class="table-container" id="place_table">
      <thead>
        <tr>
          <th style="display: none">ID</th>
          <th>NAME</th>
          <th>ADDRESS</th>
          <th>LATITUDE</th>
          <th>LONGITUDE</th>
          <th>BACKGROUND</th>
          <th>ACTION</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th style="display: none">ID</th>
          <th>NAME</th>
          <th>ADDRESS</th>
          <th>LATITUDE</th>
          <th>LONGITUDE</th>
          <th>BACKGROUND</th>
          <th>ACTION</th>
        </tr>
      </tfoot>
    </table>

    <div class="small reveal" id="place_info_modal" data-reveal>
      <div id="place_info_container"></div>
      <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
</div>

<script>
  $('#place_table').DataTable({
    "lengthMenu": [ 5,10, 25, 50, 75, 100 ],
    "processing": true,
    "serverSide": true,
    "ajax": "<%= ajax_places_url %>",
    columns: [ 
    { className: "dont_show", searchable: false, orderable: false }, 
    { }, 
    { searchable: false, orderable: false }, 
    { searchable: false, orderable: false },
    { searchable: false, orderable: false },
    { searchable: false, orderable: false },
    { searchable: false, orderable: false }  
    ] 
  });
</script>

app/views/places/new.html.erb
<%= render "form"%>

app/views/places/show.html.erb
<div class="row body_container">
  <div class="small-12 large-12 columns">
    Name: <%= @place.name %><br>
    Addres: <%= @place.address %><br>
    Latitude: <%= @place.lat %><br>
    Longitude: <%= @place.lng %><br>
    Background set: <%= image_tag @place.background.url(:medium) %><br><br>
    Photos: 

    <div class="photo_gallery">
      <% @place.photos.each { |photo| %>
        <div class="slick-slide"><%= image_tag photo.try(:image).url(:medium) %></div>
      <%  } %>
    </div>

    <%= link_to "Places", places_path %> | <%= link_to "Edit", edit_place_path(@place) %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('.photo_gallery').slick({
      accessibility: true,
      arrows: true,
      dots: true,
      slidesToShow: 3,
      slidesToScroll: 1,
      autoplay: true,
      autoplaySpeed: 2000,
    });
  });
</script>

app/views/places/show.js.erb
$("#place_info_container").html('');
$("#place_info_modal").foundation('open');
$("#place_info_container").html('<%= j render "info", xray: false %>');