config/routes.rb
Rails.application.routes.draw do

  mount Sidekiq::Web => "/sidekiq" # monitoring console
  mount API::Base => '/'

  devise_for :users, :controllers => { 
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'registrations' 
  }

  authenticated :user do
     devise_scope :user do
        root "analytics#index"
        get 'users/user_list', to: 'users#user_list', as: 'user_list'
        resources :users
        post "/users/:id/availability", to: "users#availability", as: "update_availability_user"
        delete "/users/:id/photos/:photo_id", to: "users#delete_photo", as: "delete_user_photo"
        get "/ajax_users", to: "users#ajax_users", as: "ajax_users"
        get "users/:id/followed_places", to: "users#followed_places", as: "user_followed_places"

        resources :places
        post "/places/:id/availability", to: "places#availability", as: "update_availability_place"
        delete "/places/:id/photos/:photo_id", to: "places#delete_photo", as: "delete_place_photo"
        get "/ajax_places", to: "places#ajax_places", as: "ajax_places"

        resources :photos
        get "/analytics", to: "analytics#index"
        get "/ajax_analytics_place", to: "analytics#ajax_analytics_place", as: "ajax_analytics_place"
        get "/ajax_analytics_user", to: "analytics#ajax_analytics_user", as: "ajax_analytics_user"
        get "/ajax_analytics_places_followed/:id", to: "analytics#ajax_analytics_places_followed", as: "ajax_analytics_places_followed"

        get "/notifications/new", to: "notifications#new", as: "new_notification"
        get "/notifications", to: "notifications#index", as: "notifications"
        get "/notifications/:id", to: "notifications#show", as: "notification"
        get "/ajax_notifications", to: "notifications#ajax_notifications", as: "ajax_notifications"
        post "/notifications", to: "notifications#create"

     end
  end

  unauthenticated :user do
    devise_scope :user do
      root to: "devise/sessions#new", as: "login"
      get "/users/sign_up", to: "devise/sessions#new"
    end

    get '/faq', to: 'home#faq'
    get '/terms-of-service', to: 'home#terms'
  end

end

app/helpers/layout_helper.rb
module LayoutHelper
  # Used to achieve nested layouts without content_for. This helper relies on
  # Rails internals, so beware that it make break with future major versions
  # of Rails. Inspired by http://stackoverflow.com/a/18214036
  #
  # Usage: For example, suppose "child" layout extends "parent" layout.
  # Use <%= yield %> as you would with non-nested layouts, as usual. Then on
  # the very last line of layouts/child.html.erb, include this:
  #
  #     <% parent_layout "parent" %>
  #
  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(:file => "layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/views/layouts/_footer.html.erb
<div class="footer_container"></div>

app/views/layouts/_header.html.erb
<div class="header_top_container">
  <div class="row">
    <div class="small-6 large-6 columns">
      <div class="header_left_container">
        <%= link_to image_tag("admin/Icon.png"), analytics_path , class: "header_icon"%>
      </div>
    </div>
    <div class="small-6 large-6 columns">
      <div class="header_right_container">
        <ul class="dropdown menu" data-dropdown-menu>
          <li><%= current_user.email %></li>
          <li>
            <a href="#"><%= image_tag current_user.avatar.url(:thumb), class: "img_circle" %></a>
            <ul class="menu vertical">
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Log out" , destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="header_bottom_container">
  <div class="row">
    <div class="top-bar adjust-top-bar">
      <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
          <% 
            uri = request.fullpath.split('/').second 
          %>
          <li <% if uri == "analytics" %> class="header_main_links" <% end; %> ><%= link_to "Analytics", analytics_path %></li>
          <li <% if uri == "users" %> class="header_main_links" <% end; %> ><%= link_to "User Manager", users_path %></li>
          <li <% if uri == "places" %> class="header_main_links" <% end; %> ><%= link_to "Places Manager", places_path %></li>
          <li <% if uri == "#" %> class="header_main_links" <% end; %> ><%= link_to "Notifications Manager", notifications_path %></li>
        </ul>
      </div>

      <% if @create_path %>
        <div class="top-bar-right">
          <%= form_tag @create_path, :method => 'get' do %>
            <ul class="menu">
              <% if @places.present? %>
                  <li><%= link_to "Create Places", new_place_path %></li>
              <% elsif @users.present? %>
                  <li><%= link_to "Create User", new_user_path %></li>
              <% else %>
                  <li><%= link_to "Send Notification", new_notification_path %></li>
              <% end %>
              <!--
              <li><%= text_field_tag :search, params[:search], placeholder: "Search" %></li>
              <li><%= submit_tag "Search", name: nil, class: "button"%></li>
              -->
            </ul>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<%# The "application" layout is the default layout. It extends "base"  %>
<%# to include things like header, footer, and alerts that are common  %>
<%# to most (but not all) views.                                       %>

<% if user_signed_in? %>
<%= render("layouts/header") %>
<% end %>
<%= yield :form_errors %>
<%= yield %>

<% if user_signed_in? %>
<%= render("layouts/footer") %>
<% end %>
<% parent_layout "base" %>

app/views/layouts/base.html.erb
<%# The "base" layout contains boilerplate common to *all* views. %>

<!DOCTYPE html>
<html>
  <head>
    <!-- Tipple <%= Rails.application.config.version %> (<%= l(Rails.application.config.version_time) %>) -->

    <%# CSS should go closest to the top of the document as possible. %>
    <%= stylesheet_link_tag "slick" %>
    <!-- Add the slick-theme.css if you want default styling -->
    <%= stylesheet_link_tag "slick-theme" %>
    <%= stylesheet_link_tag("application", :media => "all") %>
    <%= stylesheet_link_tag "foundation-datepicker.min" %>
    <%= stylesheet_link_tag "style" %>

    <%# JavaScript must be in head for Turbolinks to work. %>
    <%= javascript_include_async_tag("application") %>
    <%= stylesheet_link_tag "jquery-ui" %>
    <%= javascript_include_tag "jquery-ui" %>

    <%= javascript_include_tag "foundation-datepicker.min" %>
    <%= yield(:head) %>

    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/dataTables.foundation.min.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/buttons/1.2.1/css/buttons.foundation.min.css"/>
    <!-- <%= stylesheet_link_tag "datatables_foundation" %> -->

    <script type="text/javascript" src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/1.10.12/js/dataTables.foundation.min.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/buttons/1.2.1/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/buttons/1.2.1/js/buttons.foundation.min.js"></script>
  <!--   <%= javascript_include_tag "jquery.dataTables.min" %>
    <%= javascript_include_tag "dataTables.foundation.min" %>
    <%= javascript_include_tag "dataTables.buttons.min" %>
    <%= javascript_include_tag "buttons.foundation.min" %> -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%# Specifies the default name of home screen bookmark in iOS 6+ %>
    <meta name="apple-mobile-web-app-title" content="Tipple">

    <%= csrf_meta_tags %>

    <title>
      <%= strip_tags(yield(:title)) + " – " if content_for?(:title) %>
      Tipple
    </title>
  </head>
  <body>
    <div class="holder">
      <%= yield %>
    </div>
  <%= javascript_include_tag "slick.min" %>
  </body>
</html>